config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'rounds#index'

  resources :players
  resources :rounds, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
# frozen_string_literal: true

class Bet < ApplicationRecord
  enum target: %i[verde rojo negro]
  belongs_to :round
  belongs_to :player

  def player_bet
    self.amount = if player.balance <= 1000
                    player.balance
                  elsif Forecast.comming_hot_days?
                    (rand(0.03..0.07) * player.balance)
                  else
                    (rand(0.08...0.15) * player.balance)
                  end
  end
end

app/models/forecast.rb
# frozen_string_literal: true

class Forecast < ApplicationRecord
  def self.request_forecast
    uri = URI('https://api.darksky.net/forecast/b8127dbf2250d1f3902484ce83d11aac/-33.440729,-70.669443?exclude=[minutely,hourly]&units=ca')
    response = Net::HTTP.get(uri)
    res = JSON.parse(response)
    res['daily']['data'].each do |day|
      create_with(hot: day['temperatureHigh'] > 20)
        .find_or_create_by(date: DateTime.strptime(day['time'].to_s, '%s'))
    end
  end

  def self.comming_hot_days?
    request_forecast if count.zero?
    where(date: Date.today..Date.today + 7.days).pluck(:hot).include?(true)
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  has_many :bets
  has_many :rounds, through: :bets

  def self.daily_charge
    all.each do |player|
      player.balance += 10_000
      player.save
    end
  end
end

app/models/round.rb
# frozen_string_literal: true

class Round < ApplicationRecord
  paginates_per 10
  before_create :update_pot
  enum result: %i[verde rojo negro]
  has_many :bets
  has_many :players, through: :bets

  def self.play_round
    round = new(result: Round.target, pot: 0)
    Player.where('balance > 0').each do |player|
      bet = round.bets.new(player: player, round: round, target: Round.target)
      player.balance -= bet.player_bet
      round.pay_round(bet) if round.result == bet.target
      player.save
    end
    round.save!
  end

  def self.target
    case rand(100)
    when 0..2 then :verde
    when 3..49 then :rojo
    when 50..100 then :negro
    end
  end

  def pay_round(bet)
    case bet.target
    when 'verde' then bet.player.balance += bet.amount * 15
    when 'rojo' then bet.player.balance += bet.amount * 2
    when 'negro' then bet.player.balance += bet.amount * 2
    end
  end

  private

  def update_pot
    self.pot = bets.sum(&:amount)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show; end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit; end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:name, :lastname, :balance)
  end
end

app/controllers/rounds_controller.rb
# frozen_string_literal: true

class RoundsController < ApplicationController
  def index
    @rounds = Round.all.page(params[:page])
  end

  def show
    @round = Round.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/helpers/round_helper.rb
# frozen_string_literal: true

module RoundHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RouletteTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.lastname %></td>
        <td><%= player.balance %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %> |
<%= link_to 'Rounds', root_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @player.lastname %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @player.balance %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/round/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rondas</h1>

<table>
  <thead>
    <tr>
      <th>Ronda</th>
      <th>Resultado</th>
      <th>Pote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.id %></td>
        <td><%= round.result %></td>
        <td><%= round.pot %></td>
        <td><%= link_to 'Show', round %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Round</th>
      <th>Result</th>
      <th>Pot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.id %></td>
        <td><%= round.result %></td>
        <td><%= round.pot %></td>
        <td><%= link_to 'Show', round %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= paginate @rounds %>

<%= link_to 'Players', players_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Round:</strong>
  <%= @round.id %>
</p>

<p>
  <strong>Result:</strong>
  <%= @round.result %>
</p>

<p>
  <strong>Pot:</strong>
  <%= @round.pot %>
</p>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Bet</th>
      <th>Target</th>
    </tr>
  </thead>

  <tbody>
    <% @round.bets.each do |bet| %>
      <tr>
        <td><%= bet.player.name %> <%= bet.player.lastname%></td>
        <td><%= bet.amount %></td>
        <td><%= bet.target %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', root_path %>